In [2]:
import torch

### Vector
Vector is a 2D 

In [3]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

### Matrix
Matrix is 3D

In [6]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

### Tensor
Tensor is a method of representating real life data in numerical format
Its an N-D matrix


In [9]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [12]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(2,3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.7733, 0.8063, 0.5632, 0.7603],
          [0.9750, 0.4480, 0.0588, 0.5012],
          [0.1156, 0.7415, 0.8688, 0.6611]],
 
         [[0.5360, 0.4489, 0.6339, 0.9904],
          [0.3783, 0.5693, 0.5700, 0.6497],
          [0.1031, 0.6646, 0.6038, 0.4622]]]),
 torch.float32)

In [13]:
random_tensor.ndim

3

### Zeros and ones Tensors


In [14]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [15]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating Tensors with range

In [16]:
range_tensor = torch.arange(0,10,2)
range_tensor

tensor([0, 2, 4, 6, 8])

In [17]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=range_tensor) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor DataTypes

default is float32

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [18]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

### Tensor Operations

Operations.
1. Addition
2. subtractrion
3. Multiplication
4. Division

In [20]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [21]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

### Matrix multiplication 

In [22]:
tensor = torch.tensor([1, 2, 3])
tensor.shape, tensor

(torch.Size([3]), tensor([1, 2, 3]))

In [23]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [24]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [25]:
tensor @ tensor

tensor(14)

In [26]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [27]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
random_tensor_A.shape,random_tensor_B.shape



Tensor A:
tensor([[0.1778, 0.5071, 0.8493, 0.5972],
        [0.2366, 0.6262, 0.0646, 0.8067],
        [0.7119, 0.5024, 0.5369, 0.8768]])

Tensor B:
tensor([[0.4907, 0.1665, 0.9030, 0.9342],
        [0.3794, 0.7570, 0.4343, 0.8396],
        [0.6942, 0.1140, 0.8085, 0.2842]])



(torch.Size([3, 4]), torch.Size([3, 4]))

In [28]:
output = torch.matmul(random_tensor_A.T,random_tensor_B)
output, output.shape

(tensor([[0.6712, 0.2899, 0.8389, 0.5671],
         [0.8352, 0.6158, 1.1361, 1.1423],
         [0.8140, 0.2515, 1.2290, 1.0002],
         [1.2079, 0.8101, 1.5986, 1.4845]]),
 torch.Size([4, 4]))

###  min, max, mean, sum

In [29]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [31]:
x.min() , torch.min(x)

(tensor(0), tensor(0))

In [32]:
torch.mean(x.type(torch.float32))


tensor(45.)

In [33]:
#index of max element
tensor.argmax()

tensor(2)

In [34]:
#index of min elemenmt
tensor.argmin()

tensor(0)

### Reshaping, stacking, squeezing and unsqueezing
reshaping:

In [35]:
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [36]:
## Reshape add extra dimension
re_shape_tensor = x.reshape(2,5)
re_shape_tensor, re_shape_tensor.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [37]:
## View 
# View is a reference of x
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [38]:
## Stack tensors on top
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [39]:
y_stacked = torch.stack([x, x, x], dim=1)
y_stacked

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [40]:
##Squeeze reduces the dimention to 1
x_reshaped = x.reshape(1, 10)
x_squeezed = x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [41]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [42]:
## Permute
# Create tensor with specific shape
x_original = torch.rand(size=(223, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([223, 224, 3])
New shape: torch.Size([3, 223, 224])


### Indexing

In [43]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [44]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [45]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]
x[:, :, 1]

tensor([[2, 5, 8]])

In [46]:
x[:, 1, :]

tensor([[4, 5, 6]])

### Pytorch tensors and numpy


In [47]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0705, 0.9184, 0.5915, 0.3047],
        [0.2041, 0.6212, 0.2270, 0.6701],
        [0.0475, 0.3952, 0.0559, 0.6485]])

Tensor B:
tensor([[0.9272, 0.1927, 0.3796, 0.5654],
        [0.3227, 0.8715, 0.3263, 0.4942],
        [0.7402, 0.9422, 0.7867, 0.8229]])



tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [49]:
!nvidia-smi

Wed Feb 19 09:33:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro T1000                 WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   61C    P8              3W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [50]:
import torch
torch.cuda.is_available()

False

### Sample Linear regression 
with salary data from kaggle (https://www.kaggle.com/datasets/karthickveerakumar/salary-data-simple-linear-regression/data)
the data have 2 columns years of experience (x) and salary (y)


In [51]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


In [52]:
df=pd.read_csv("Salary_Data.csv")
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [55]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes


YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [ ]:
plt.scatter(df['YearsExperience'],df['Salary'])