In [1]:
import torch

### Vector
Vector is a 2D 

In [3]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

### Matrix
Matrix is 3D

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

### Tensor
Tensor is a method of representating real life data in numerical format
Its an N-D matrix


In [10]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(2,3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.3435, 0.2913, 0.2947, 0.9898],
          [0.2317, 0.8092, 0.7716, 0.5784],
          [0.7338, 0.0993, 0.3600, 0.4433]],
 
         [[0.8907, 0.3203, 0.6719, 0.7984],
          [0.4691, 0.8044, 0.4884, 0.3668],
          [0.4013, 0.5776, 0.6627, 0.2072]]]),
 torch.float32)

In [17]:
random_tensor.ndim

3

### Zeros and ones Tensors


In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating Tensors with range

In [24]:
range_tensor = torch.arange(0,10,2)
range_tensor

tensor([0, 2, 4, 6, 8])

In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=range_tensor) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor DataTypes

default is float32

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [27]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

### Tensor Operations

Operations.
1. Addition
2. subtractrion
3. Multiplication
4. Division

In [45]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

### Matrix multiplication 

In [49]:
tensor = torch.tensor([1, 2, 3])
tensor.shape, tensor

(torch.Size([3]), tensor([1, 2, 3]))

In [48]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [50]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
tensor @ tensor

tensor(14)

In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [56]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
random_tensor_A.shape,random_tensor_B.shape



Tensor A:
tensor([[0.5507, 0.1869, 0.9568, 0.1820],
        [0.2385, 0.7663, 0.5686, 0.0927],
        [0.4903, 0.6554, 0.1963, 0.9137]])

Tensor B:
tensor([[0.7957, 0.5379, 0.0836, 0.7631],
        [0.0931, 0.2952, 0.7910, 0.2789],
        [0.4984, 0.6976, 0.9674, 0.3147]])



(torch.Size([3, 4]), torch.Size([3, 4]))

In [61]:
output = torch.matmul(random_tensor_A.T,random_tensor_B)
output, output.shape

(tensor([[0.7048, 0.7086, 0.7090, 0.6411],
         [0.5468, 0.7840, 1.2559, 0.5626],
         [0.9121, 0.8194, 0.7196, 0.9505],
         [0.6088, 0.7626, 0.9724, 0.4522]]),
 torch.Size([4, 4]))

###  min, max, mean, sum

In [62]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [65]:
x.min() , torch.min(x)

(tensor(0), tensor(0))

In [67]:
torch.mean(x.type(torch.float32))


tensor(45.)

In [68]:
#index of max element
tensor.argmax()

tensor(2)

In [70]:
#index of min elemenmt
tensor.argmin()

tensor(0)

### Reshaping, stacking, squeezing and unsqueezing
reshaping:

In [75]:
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [83]:
## Reshape add extra dimension
re_shape_tensor = x.reshape(2,5)
re_shape_tensor, re_shape_tensor.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [86]:
## View 
# View is a reference of x
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [89]:
## Stack tensors on top
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [90]:
y_stacked = torch.stack([x, x, x], dim=1)
y_stacked

tensor([[ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [98]:
##Squeeze reduces the dimention to 1
x_reshaped = x.reshape(1, 10)
x_squeezed = x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [102]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


In [106]:
## Permute
# Create tensor with specific shape
x_original = torch.rand(size=(223, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([223, 224, 3])
New shape: torch.Size([3, 223, 224])


### Indexing

In [107]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [108]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [111]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]
x[:, :, 1]

tensor([[2, 5, 8]])

In [114]:
x[:, 1, :]

tensor([[4, 5, 6]])

### Pytorch tensors and numpy


In [115]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

False

In [118]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0765, 0.7838, 0.8390, 0.1573],
        [0.7050, 0.2449, 0.7707, 0.7737],
        [0.3406, 0.9207, 0.8740, 0.2480]])

Tensor B:
tensor([[0.8595, 0.1284, 0.8002, 0.8500],
        [0.0791, 0.3819, 0.3706, 0.2402],
        [0.1775, 0.9889, 0.9961, 0.4355]])



tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [119]:
!nvidia-smi

Mon Feb 10 07:54:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro T1000                 WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   57C    P8              2W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [121]:
import torch
torch.cuda.is_available()

False